In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [3]:
tf.__version__

'1.14.0'

In [4]:
cm = pd.read_csv('Churn_Modelling.csv')

In [5]:
cm.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [6]:
X = cm.iloc[:,3:-1].values
y = cm.iloc[:,-1].values

In [7]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
print(y)

[1 0 1 ... 1 1 0]


Encoding categorical data

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [10]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


one hot Encoding in 'Geography' column

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

Feature Scaling is fundamental in DL, and must be done in on all features

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

Building the ANN with two hidden layer

In [15]:
from keras.models import Sequential
ann = tf.keras.models.Sequential()

Using TensorFlow backend.


Adding the input and first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the output layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

Training the ANN

In [22]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
#optimizer adam for stachastic gradient descent
#loss binary_crossentropy because output has to be in binary
#metrics

Training ANN on training set

In [23]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)
#batch_size 32 selected being default

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
8000/8000 [==============================] - 0s 46us/sample - loss: 0.6704 - acc: 0.6135
Epoch 2/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.4879 - acc: 0.7974
Epoch 3/100
8000/8000 [==============================] - 0s 34us/sample - loss: 0.4416 - acc: 0.8086
Epoch 4/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.4265 - acc: 0.8152
Epoch 5/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.4211 - acc: 0.8177
Epoch 6/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.4176 - acc: 0.8179
Epoch 7/100
8000/8000 [==============================] - 0s 33us/sample - loss: 0.4143 - acc: 0.8192
Epoch 8/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.4114 - acc: 0.8215
Epoch 9/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.4090 - acc: 0.82

8000/8000 [==============================] - 0s 32us/sample - loss: 0.3335 - acc: 0.8636
Epoch 79/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.3331 - acc: 0.8631
Epoch 80/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.3331 - acc: 0.8659
Epoch 81/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.3333 - acc: 0.8643
Epoch 82/100
8000/8000 [==============================] - 0s 27us/sample - loss: 0.3332 - acc: 0.8646
Epoch 83/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.3332 - acc: 0.8639
Epoch 84/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3330 - acc: 0.8635
Epoch 85/100
8000/8000 [==============================] - 0s 31us/sample - loss: 0.3329 - acc: 0.8640
Epoch 86/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.3329 - acc: 0.8650
Epoch 87/100
8000/8000 [==============================] - 0s 35us/sample - loss: 0.3328 - acc: 

Predicting the Test Set Results and Confusion Matrix

In [24]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [26]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))

[[1540   55]
 [ 221  184]]
              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1595
           1       0.77      0.45      0.57       405

    accuracy                           0.86      2000
   macro avg       0.82      0.71      0.74      2000
weighted avg       0.85      0.86      0.85      2000



Predicting result for below mentioned person

In [28]:
#To find out if the customer's gonna leave the bank

#Customer info
#Geography : France
#Credit Score :600
#Gender : Male
#Age :40
#Tenure : 3
#Balance : 60000
#No of products : 2
#credit card? Yes
#Active? Yes
#Est. Salary : 50000

In [29]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

[[0.01803063]]


In [30]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)
#To put in statement than percentage

[[False]]
